<div class="battle-cube <?= $this->classes ?>">
    <div class="line numbers">
        <span>1</span><span>2</span><span>3</span><span>4</span><span>5</span><span>6</span><span>7</span><span>8</span><span>9</span><span>10</span>
    </div>
    <div class="line letters">
        <span>А</span><span>Б</span><span>В</span><span>Г</span><span>Д</span><span>Е</span><span>Ж</span><span>З</span><span>И</span><span>К</span>
    </div>
    <div class="field-container">
        <?
        if ($this->showOverlay) {
            ?><div class="field field-overlay"><?

            for ($y = 0; $y < $this->size; $y++) {
                ?><div class="row" data-row="<?= $y ?>"><?

                for ($x = 0; $x < $this->size; $x++) {
                    ?><div class="cell" data-col="<?= $x ?>"></div><?
                }

                ?></div><?
            }
            ?></div><?
        }
        ?>
        <div class="field field-graphics"><?

            for ($y = 0; $y < $this->size; $y++) {
                ?><div class="row" data-row="<?= $y ?>"><?

                for ($x = 0; $x < $this->size; $x++) {
                    ?><div class="cell" data-col="<?= $x ?>"></div><?
                }

                ?></div><?
            }
            ?></div>
    </div>
</div>