<div class="ships-damage">
    <div class="row">
        <div class="ship-dmg" data-type="4-1"><i></i><i></i><i></i><i></i></div>
    </div>
    <div class="row">
        <div class="ship-dmg" data-type="3-1"><i></i><i></i><i></i></div>
        <div class="ship-dmg" data-type="3-2"><i></i><i></i><i></i></div>
    </div>
    <div class="row">
        <div class="ship-dmg" data-type="2-1"><i></i><i></i></div>
        <div class="ship-dmg" data-type="2-2"><i></i><i></i></div>
        <div class="ship-dmg" data-type="2-3"><i></i><i></i></div>
    </div>
    <div class="row">
        <div class="ship-dmg" data-type="1-1"><i></i></div>
        <div class="ship-dmg" data-type="1-2"><i></i></div>
        <div class="ship-dmg" data-type="1-3"><i></i></div>
        <div class="ship-dmg" data-type="1-4"><i></i></div>
    </div>
</div>