/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.mafiaheader;
import javax.swing.*;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;
/**
 *
 * @author Андрей
 */

public class MafiaHeader extends javax.swing.JFrame {
    
    /**
     * Creates new form MafiaHeader
     */
    private Constants c;  //тут хранятся все константы
    private Player[] players;  //массив игроков
    
    private Game game;
    
    /* Для вывода лога в textpane*/
    private int rowCount;
    private static AttributeSet set0;
    StyledDocument doc;
    
    public MafiaHeader() {
        initComponents();
        c=new Constants();
        doc= Log_Text.getStyledDocument();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    JFrame JFrame2;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GamePlacePanel = new javax.swing.JPanel();
        Player_0 = new javax.swing.JButton();
        Player_1 = new javax.swing.JButton();
        Player_2 = new javax.swing.JButton();
        Player_3 = new javax.swing.JButton();
        Player_4 = new javax.swing.JButton();
        Player_5 = new javax.swing.JButton();
        Player_6 = new javax.swing.JButton();
        Player_7 = new javax.swing.JButton();
        Player_8 = new javax.swing.JButton();
        Player_9 = new javax.swing.JButton();
        Player_10 = new javax.swing.JButton();
        Player_11 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        GameChatLabel = new javax.swing.JLabel();
        GamePlaceLabel = new javax.swing.JLabel();
        InfoPanel = new javax.swing.JPanel();
        NameGameStats = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        GameStatsTextPane = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        Log_Text = new javax.swing.JTextPane();
        ButtonPanel = new javax.swing.JPanel();
        StartGameButton = new javax.swing.JButton();
        RulesButton = new javax.swing.JButton();
        ExitProgButton = new javax.swing.JButton();
        SetRolesButton = new javax.swing.JButton();
        StepByStep = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAFIA");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(200, 100));
        setResizable(false);

        GamePlacePanel.setBackground(new java.awt.Color(57, 115, 77));
        GamePlacePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Player_0.setBackground(new java.awt.Color(153, 0, 204));
        Player_0.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        Player_0.setForeground(new java.awt.Color(255, 255, 255));
        Player_0.setText("?");
        Player_0.setToolTipText("Player #0");
        Player_0.setEnabled(false);
        Player_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player_0ActionPerformed(evt);
            }
        });

        Player_1.setBackground(new java.awt.Color(153, 0, 204));
        Player_1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        Player_1.setForeground(new java.awt.Color(255, 255, 255));
        Player_1.setText("?");
        Player_1.setToolTipText("Player #1");
        Player_1.setEnabled(false);
        Player_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player_1ActionPerformed(evt);
            }
        });

        Player_2.setBackground(new java.awt.Color(153, 0, 204));
        Player_2.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        Player_2.setForeground(new java.awt.Color(255, 255, 255));
        Player_2.setText("?");
        Player_2.setToolTipText("Player #2");
        Player_2.setEnabled(false);
        Player_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player_2ActionPerformed(evt);
            }
        });

        Player_3.setBackground(new java.awt.Color(153, 0, 204));
        Player_3.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        Player_3.setForeground(new java.awt.Color(255, 255, 255));
        Player_3.setText("?");
        Player_3.setToolTipText("Player #3");
        Player_3.setEnabled(false);
        Player_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player_3ActionPerformed(evt);
            }
        });

        Player_4.setBackground(new java.awt.Color(153, 0, 204));
        Player_4.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        Player_4.setForeground(new java.awt.Color(255, 255, 255));
        Player_4.setText("?");
        Player_4.setToolTipText("Player #4");
        Player_4.setEnabled(false);
        Player_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player_4ActionPerformed(evt);
            }
        });

        Player_5.setBackground(new java.awt.Color(153, 0, 204));
        Player_5.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        Player_5.setForeground(new java.awt.Color(255, 255, 255));
        Player_5.setText("?");
        Player_5.setToolTipText("Player #5");
        Player_5.setEnabled(false);
        Player_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player_5ActionPerformed(evt);
            }
        });

        Player_6.setBackground(new java.awt.Color(153, 0, 204));
        Player_6.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        Player_6.setForeground(new java.awt.Color(255, 255, 255));
        Player_6.setText("?");
        Player_6.setToolTipText("Player #6");
        Player_6.setEnabled(false);
        Player_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player_6ActionPerformed(evt);
            }
        });

        Player_7.setBackground(new java.awt.Color(153, 0, 204));
        Player_7.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        Player_7.setForeground(new java.awt.Color(255, 255, 255));
        Player_7.setText("?");
        Player_7.setToolTipText("Player #7");
        Player_7.setActionCommand("#7");
        Player_7.setEnabled(false);
        Player_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player_7ActionPerformed(evt);
            }
        });

        Player_8.setBackground(new java.awt.Color(153, 0, 204));
        Player_8.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        Player_8.setForeground(new java.awt.Color(255, 255, 255));
        Player_8.setText("?");
        Player_8.setToolTipText("Player #8");
        Player_8.setEnabled(false);
        Player_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player_8ActionPerformed(evt);
            }
        });

        Player_9.setBackground(new java.awt.Color(153, 0, 204));
        Player_9.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        Player_9.setForeground(new java.awt.Color(255, 255, 255));
        Player_9.setText("?");
        Player_9.setToolTipText("Player #9");
        Player_9.setEnabled(false);
        Player_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player_9ActionPerformed(evt);
            }
        });

        Player_10.setBackground(new java.awt.Color(153, 0, 204));
        Player_10.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        Player_10.setForeground(new java.awt.Color(255, 255, 255));
        Player_10.setText("?");
        Player_10.setToolTipText("Player #10");
        Player_10.setEnabled(false);
        Player_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player_10ActionPerformed(evt);
            }
        });

        Player_11.setBackground(new java.awt.Color(153, 0, 204));
        Player_11.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        Player_11.setForeground(new java.awt.Color(255, 255, 255));
        Player_11.setText("?");
        Player_11.setToolTipText("Player #11");
        Player_11.setEnabled(false);
        Player_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player_11ActionPerformed(evt);
            }
        });

        label1.setText("0");

        label2.setText("1");

        label3.setText("2");

        label4.setText("3");

        label5.setText("4");

        label6.setText("5");

        label7.setText("6");

        label8.setText("7");

        label9.setText("8");

        label10.setText("9");

        label11.setText("10");

        label12.setText("11");

        javax.swing.GroupLayout GamePlacePanelLayout = new javax.swing.GroupLayout(GamePlacePanel);
        GamePlacePanel.setLayout(GamePlacePanelLayout);
        GamePlacePanelLayout.setHorizontalGroup(
            GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamePlacePanelLayout.createSequentialGroup()
                .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GamePlacePanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(Player_4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePlacePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Player_2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GamePlacePanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Player_1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player_5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(GamePlacePanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GamePlacePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GamePlacePanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Player_0, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player_6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePlacePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)))
                .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(GamePlacePanelLayout.createSequentialGroup()
                        .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Player_7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player_11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 139, Short.MAX_VALUE))
                    .addGroup(GamePlacePanelLayout.createSequentialGroup()
                        .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GamePlacePanelLayout.createSequentialGroup()
                                .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(GamePlacePanelLayout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePlacePanelLayout.createSequentialGroup()
                                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(Player_8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(GamePlacePanelLayout.createSequentialGroup()
                                .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(GamePlacePanelLayout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Player_10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePlacePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Player_3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Player_9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        GamePlacePanelLayout.setVerticalGroup(
            GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamePlacePanelLayout.createSequentialGroup()
                .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GamePlacePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Player_0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GamePlacePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(GamePlacePanelLayout.createSequentialGroup()
                                .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Player_1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player_11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(GamePlacePanelLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePlacePanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(GamePlacePanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Player_10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Player_2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GamePlacePanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Player_9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player_3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(GamePlacePanelLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GamePlacePanelLayout.createSequentialGroup()
                        .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Player_8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Player_7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player_5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(GamePlacePanelLayout.createSequentialGroup()
                        .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GamePlacePanelLayout.createSequentialGroup()
                                .addComponent(Player_4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 21, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePlacePanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(GamePlacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Player_6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );

        GameChatLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GameChatLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GameChatLabel.setText("Игровой чат");

        GamePlaceLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GamePlaceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GamePlaceLabel.setText("Игровое поле");

        InfoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NameGameStats.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NameGameStats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameGameStats.setText("Характеристики");

        GameStatsTextPane.setEditable(false);
        GameStatsTextPane.setBackground(new java.awt.Color(249, 229, 255));
        jScrollPane2.setViewportView(GameStatsTextPane);

        Log_Text.setEditable(false);
        Log_Text.setBackground(new java.awt.Color(249, 229, 255));
        Log_Text.setForeground(new java.awt.Color(153, 0, 0));
        jScrollPane3.setViewportView(Log_Text);

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameGameStats, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
            .addComponent(jScrollPane2)
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameGameStats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ButtonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        StartGameButton.setText("Начать игру!");
        StartGameButton.setEnabled(false);
        StartGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameButtonActionPerformed(evt);
            }
        });

        RulesButton.setText("Правила игры");
        RulesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RulesButtonActionPerformed(evt);
            }
        });

        ExitProgButton.setText("Выход");
        ExitProgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitProgButtonActionPerformed(evt);
            }
        });

        SetRolesButton.setText("Раздать роли");
        SetRolesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetRolesButtonActionPerformed(evt);
            }
        });

        StepByStep.setText("По шагам");
        StepByStep.setEnabled(false);
        StepByStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StepByStepActionPerformed(evt);
            }
        });

        RefreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/mafiaheader/imagepackage/refresh.jpg"))); // NOI18N
        RefreshButton.setEnabled(false);
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RulesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StepByStep, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(SetRolesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(ExitProgButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(StartGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SetRolesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StartGameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StepByStep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RulesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitProgButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GamePlacePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GamePlaceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GameChatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GamePlaceLabel)
                    .addComponent(GameChatLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GamePlacePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void WriteLog(int type,String s){  //выводит сообщение в лог, окрашивает их в разные цвета в зависимости от содержания
        if(type==0){//запуск, остановка
            set0=StyleContext.getDefaultStyleContext().addAttribute(SimpleAttributeSet.EMPTY, StyleConstants.Foreground, Color.MAGENTA);
        }
        if(type==1){//док полечил
            set0=StyleContext.getDefaultStyleContext().addAttribute(SimpleAttributeSet.EMPTY, StyleConstants.Foreground, Color.GREEN);
        }
        if(type==2){//обычное сообщение
            set0=StyleContext.getDefaultStyleContext().addAttribute(SimpleAttributeSet.EMPTY, StyleConstants.Foreground, Color.DARK_GRAY);
        }
        if(type==3){//игрока повесили
            set0=StyleContext.getDefaultStyleContext().addAttribute(SimpleAttributeSet.EMPTY, StyleConstants.Foreground, Color.RED);
        }
        try {
            doc.insertString(doc.getLength(),Integer.toString(rowCount) + "-й ход: "+ s + "\n", set0);
        } catch (BadLocationException ex) {
            Logger.getLogger(MafiaHeader.class.getName()).log(Level.SEVERE, null, ex);
        }
        rowCount++;
    }   
    private void obolochka(int n,JButton Player,Mafia[] mafias,Doctor doctor){
        //нарисуем картинки на кнопках:
        for(int i=0;i<2;i++){  //мафия?
            if(mafias[i].number==n)
            {
                Player.setText("");
                Player.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/mafiaheader/imagepackage/maf.jpg")));
                return;
            }
        }
        //доктор?
        if(doctor.number==n){
            Player.setText("");
            Player.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/mafiaheader/imagepackage/doc.jpg")));
            return;
        }
        //ну тогда мирный
        Player.setText("");
        Player.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/mafiaheader/imagepackage/ctz.jpg")));
    }
    private void Player_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player_0ActionPerformed
        Player player = new Player();
        player.Set_from_player(players[0]);
        GameStatsTextPane.setText("Красноречие: " + player.getOratory() + "\nХаризма: " + player.getCharisma() + "\nУдача: " + player.getLucky() + "\nДоверчивость: " + player.getNaivete());
    }//GEN-LAST:event_Player_0ActionPerformed

    private void Player_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player_1ActionPerformed
        // TODO add your handling code here:
        Player player = new Player();  
        player.Set_from_player(players[1]);
        GameStatsTextPane.setText("Красноречие: " + player.getOratory() + "\nХаризма: " + player.getCharisma() + "\nУдача: " + player.getLucky() + "\nДоверчивость: " + player.getNaivete());
    }//GEN-LAST:event_Player_1ActionPerformed

    private void Player_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player_2ActionPerformed
        // TODO add your handling code here:
        Player player = new Player();  
        player.Set_from_player(players[2]);
        GameStatsTextPane.setText("Красноречие: " + player.getOratory() + "\nХаризма: " + player.getCharisma() + "\nУдача: " + player.getLucky() + "\nДоверчивость: " + player.getNaivete());
    }//GEN-LAST:event_Player_2ActionPerformed

    private void Player_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player_3ActionPerformed
        // TODO add your handling code here:
        Player player = new Player();  
        player.Set_from_player(players[3]);
        GameStatsTextPane.setText("Красноречие: " + player.getOratory() + "\nХаризма: " + player.getCharisma() + "\nУдача: " + player.getLucky() + "\nДоверчивость: " + player.getNaivete());
    }//GEN-LAST:event_Player_3ActionPerformed

    private void Player_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player_4ActionPerformed
        // TODO add your handling code here:
        Player player = new Player();  
        player.Set_from_player(players[4]);
        GameStatsTextPane.setText("Красноречие: " + player.getOratory() + "\nХаризма: " + player.getCharisma() + "\nУдача: " + player.getLucky() + "\nДоверчивость: " + player.getNaivete());
    }//GEN-LAST:event_Player_4ActionPerformed

    private void Player_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player_5ActionPerformed
        // TODO add your handling code here:
        Player player = new Player();  
        player.Set_from_player(players[5]);
        GameStatsTextPane.setText("Красноречие: " + player.getOratory() + "\nХаризма: " + player.getCharisma() + "\nУдача: " + player.getLucky() + "\nДоверчивость: " + player.getNaivete());
    }//GEN-LAST:event_Player_5ActionPerformed

    private void Player_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player_6ActionPerformed
        // TODO add your handling code here:
        Player player = new Player(); 
        player.Set_from_player(players[6]);
        GameStatsTextPane.setText("Красноречие: " + player.getOratory() + "\nХаризма: " + player.getCharisma() + "\nУдача: " + player.getLucky() + "\nДоверчивость: " + player.getNaivete());
    }//GEN-LAST:event_Player_6ActionPerformed

    private void Player_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player_7ActionPerformed
        // TODO add your handling code here:
        Player player = new Player();  
        player.Set_from_player(players[7]);
        GameStatsTextPane.setText("Красноречие: " + player.getOratory() + "\nХаризма: " + player.getCharisma() + "\nУдача: " + player.getLucky() + "\nДоверчивость: " + player.getNaivete());
    }//GEN-LAST:event_Player_7ActionPerformed

    private void Player_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player_8ActionPerformed
        // TODO add your handling code here:
        Player player = new Player();  
        player.Set_from_player(players[8]);
        GameStatsTextPane.setText("Красноречие: " + player.getOratory() + "\nХаризма: " + player.getCharisma() + "\nУдача: " + player.getLucky() + "\nДоверчивость: " + player.getNaivete());
    }//GEN-LAST:event_Player_8ActionPerformed

    private void Player_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player_9ActionPerformed
        // TODO add your handling code here:
        Player player = new Player();  
        player.Set_from_player(players[9]);
        GameStatsTextPane.setText("Красноречие: " + player.getOratory() + "\nХаризма: " + player.getCharisma() + "\nУдача: " + player.getLucky() + "\nДоверчивость: " + player.getNaivete());
    }//GEN-LAST:event_Player_9ActionPerformed

    private void Player_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player_10ActionPerformed
        // TODO add your handling code here:
        Player player = new Player();  
        player.Set_from_player(players[10]);
        GameStatsTextPane.setText("Красноречие: " + player.getOratory() + "\nХаризма: " + player.getCharisma() + "\nУдача: " + player.getLucky() + "\nДоверчивость: " + player.getNaivete());
    }//GEN-LAST:event_Player_10ActionPerformed

    private void Player_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player_11ActionPerformed
        // TODO add your handling code here:
        Player player = new Player();  
        player.Set_from_player(players[11]);
        GameStatsTextPane.setText("Красноречие: " + player.getOratory() + "\nХаризма: " + player.getCharisma() + "\nУдача: " + player.getLucky() + "\nДоверчивость: " + player.getNaivete());
    }//GEN-LAST:event_Player_11ActionPerformed

    private void StepByStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StepByStepActionPerformed
        // по шагам
        int k=0;
        game.Night(c,this);
        k=game.Day(c,this);
        if(game.Check(this)==1){
            WriteLog(0,"Победа Мирных жителей");
            StepByStep.setEnabled(false);
            StartGameButton.setEnabled(false);
            RefreshButton.setEnabled(true);
            JOptionPane.showMessageDialog(InfoPanel, "Мирные жители освободили город от мафии!", "Победа мирных жителей", JOptionPane.INFORMATION_MESSAGE);
        }
        if(k==1){
            WriteLog(0,"Победа Мафии");
            StepByStep.setEnabled(false);
            StartGameButton.setEnabled(false);
            RefreshButton.setEnabled(true);
            JOptionPane.showMessageDialog(InfoPanel, "Мафия захватила город!", "Победа мафии", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_StepByStepActionPerformed

    private void SetRolesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetRolesButtonActionPerformed
        //раздать роли всем игрокам и очистить лог
        Mafia[] mafias;  //массив мафиози
    Citizen[] citizens;  //массив мирных
    Doctor doctor;  //один доктор
        //заполним массив players
        players=new Player[12];
        for(int i=0;i<12;i++){
            players[i]=new Player();//тут заполняем рандомными значениями каждого игрока
            players[i].set_rnd(c);
            players[i].number=i;
        }
        //раздадим роли
        int k=0;
        mafias=new Mafia[2];//2 мафии
        for(int i=0;i<2;i++){//раздаем мафию
            do{
                k=c.rnd.nextInt(12);// выбираем рандомного пользователя
            }while(players[k].ingame);//так мы ищем того кто еще не в игре
            players[k].ingame=true;
            mafias[i]=new Mafia(players[k]);
        }
        do{//раздаем доктора
            k=c.rnd.nextInt(12);// выбираем рандомного пользователя
        }while(players[k].ingame);//так мы ищем того кто еще не в игре
        players[k].ingame=true;
        doctor=new Doctor(players[k]);
        //раздаем всем оставшимся мирынх
        k=0;
        citizens=new Citizen[9];//9 мирных
        for(int i=0;i<11;i++){
            if(players[i].ingame==false){
                players[k].ingame=true;
                citizens[k]=new Citizen(players[i]);
                k++;
            }
        }
        game=new Game(mafias,citizens,doctor,players);//основной механизм игры
        //раздали все роли
        //нарисуем картинки на кнопках:
        obolochka(0,Player_0,mafias,doctor);
        obolochka(1,Player_1,mafias,doctor);
        obolochka(2,Player_2,mafias,doctor);
        obolochka(3,Player_3,mafias,doctor);
        obolochka(4,Player_4,mafias,doctor);
        obolochka(5,Player_5,mafias,doctor);
        obolochka(6,Player_6,mafias,doctor);
        obolochka(7,Player_7,mafias,doctor);
        obolochka(8,Player_8,mafias,doctor);
        obolochka(9,Player_9,mafias,doctor);
        obolochka(10,Player_10,mafias,doctor);
        obolochka(11,Player_11,mafias,doctor);
        
        Log_Text.setText("");
        rowCount=0;
        SetRolesButton.setEnabled(false);
        StepByStep.setEnabled(true);
        StartGameButton.setEnabled(true);
        Player_0.setEnabled(true);
        Player_1.setEnabled(true);
        Player_2.setEnabled(true);
        Player_3.setEnabled(true);
        Player_4.setEnabled(true);
        Player_5.setEnabled(true);
        Player_6.setEnabled(true);
        Player_7.setEnabled(true);
        Player_8.setEnabled(true);
        Player_9.setEnabled(true);
        Player_10.setEnabled(true);
        Player_11.setEnabled(true);
        RefreshButton.setEnabled(false);
    }//GEN-LAST:event_SetRolesButtonActionPerformed

    private void ExitProgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitProgButtonActionPerformed
        int response = JOptionPane.showConfirmDialog(InfoPanel, "Вы действительно хотите выйти? Это действие приведёт к завершению работы программы.", "Завершение работы", JOptionPane.YES_NO_OPTION);
        switch(response) {
            case JOptionPane.YES_OPTION:
            System.exit(0);
            break;
            case JOptionPane.NO_OPTION:
            break;
        }
    }//GEN-LAST:event_ExitProgButtonActionPerformed

    private void RulesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RulesButtonActionPerformed
        new GameRules().setVisible(true);
    }//GEN-LAST:event_RulesButtonActionPerformed

    private void StartGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameButtonActionPerformed
        //игра
        int k=0;
        do{
            game.Night(c,this);
            k=game.Day(c,this);
        }while((game.Check(this)==0)&&(k==0));
        if(game.Check(this)==1){
            WriteLog(0,"Победа Мирных жителей");
            StepByStep.setEnabled(false);
            StartGameButton.setEnabled(false);
            RefreshButton.setEnabled(true);
            JOptionPane.showMessageDialog(InfoPanel, "Мирные жители освободили город от мафии!", "Победа мирных жителей", JOptionPane.INFORMATION_MESSAGE);
            
        }
        if(k==1){
            WriteLog(0,"Победа Мафии");
            StepByStep.setEnabled(false);
            StartGameButton.setEnabled(false);
            RefreshButton.setEnabled(true);
            JOptionPane.showMessageDialog(InfoPanel, "Мафия захватила город!", "Победа мафии", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_StartGameButtonActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        SetRolesButton.setEnabled(true);
        Log_Text.setText("");
        GameStatsTextPane.setText("");
    }//GEN-LAST:event_RefreshButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
          MafiaHeader MainWin = new MafiaHeader();
          MainWin.setVisible(true);
          
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JButton ExitProgButton;
    private javax.swing.JLabel GameChatLabel;
    private javax.swing.JLabel GamePlaceLabel;
    private javax.swing.JPanel GamePlacePanel;
    private javax.swing.JTextPane GameStatsTextPane;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JTextPane Log_Text;
    private javax.swing.JLabel NameGameStats;
    private javax.swing.JButton Player_0;
    private javax.swing.JButton Player_1;
    private javax.swing.JButton Player_10;
    private javax.swing.JButton Player_11;
    private javax.swing.JButton Player_2;
    private javax.swing.JButton Player_3;
    private javax.swing.JButton Player_4;
    private javax.swing.JButton Player_5;
    private javax.swing.JButton Player_6;
    private javax.swing.JButton Player_7;
    private javax.swing.JButton Player_8;
    private javax.swing.JButton Player_9;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton RulesButton;
    private javax.swing.JButton SetRolesButton;
    private javax.swing.JButton StartGameButton;
    private javax.swing.JButton StepByStep;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
